version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - discovery.zen.minimum_master_nodes=1
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes: 
            - esdata:/usr/shre/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - esnet
    kibana:
        image: docker.elastic.co/kibana/kibana:7.12.1
        volumes:
            - ./kibana.yml/:/usr/share/kibana/config/kibana.yml
        ports: 
            - "5601:5601"
        depends_on: 
            - elasticsearch
        networks: 
            - esnet

volumes: 
    esdata:
        driver: local

networks: 
    esnet:
